CREATE TABLE tasks (
    task_id VARCHAR(100) PRIMARY KEY,
    tarefa VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
