print('Preencha sua data de nascimento de acordo com seu RG')
dia = input('Dia - ')
mes = input('Mês - ')
ano = input('Ano - ')
print('Você nasceu no dia', dia, 'do', mes, 'de', ano, '?')
simounao = input('CONFIRME COLOCANDO 1 - ')
print('Aperte Em Continuar')
