CREATE TABLE "users" (
    "user_id" VARCHAR(100) PRIMARY KEY,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "nickname" VARCHAR(50) UNIQUE,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);